@extends('partials.templatePage')

@section('page-css')
    <link href="{{ mix('/css/content-show.css') }}" rel="stylesheet">
@endsection

@section('page-head')
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    @if($content->isVideo())
            {
                "@context" : "http://schema.org",
                "@type": "VideoObject",
                "uploadDate" : "{{ $content->created_at }}",
                "name" : "{{ $content->displayName }}",
                "thumbnailUrl" : "{{ $content->thumbnail }}",
                "description" : "{{ $content->metaDescription }}",
                "contentUrl" : "{{ $content->url }}",
                "embedUrl" : "{{ route('web.c.embed' , $content->id) }}",
                "publisher" : {
                    "@type" : "Organization",
                    "name" : "آلاء",
                    "logo": {
                        "@type": "ImageObject",
                        "url": "https://cdn.alaatv.com/upload/Alaa-logo.png?w=182&h=224"
                    }
                }
        }
@endif
        @if($content->isArticle())
            {
              "@context" : "http://schema.org",
              "@type" : "Article",
              "name" : "{{ $content->displayName }}",
              "headline" : "{{ $content->displayName }}",
          @if(isset($content->author_id))
                "author" : {
                  "@type" : "Person",
                  "name" : "{{ $author }}"
                 },
          @endif
            @if($content->id == 17408)
                "image" : "https://cdn.alaatv.com/upload/article/konkur_nezam_jadid_ya_ghadim.jpg",
@endif
            @if(isset($contentSetName))
                "articleSection" : "{{ $contentSetName }}",
          @endif
            "url" : "{{ $content->url }}",
          "publisher" : {
            "@type" : "Organization",
            "name" : "آلاء",
              "logo": {
                "@type": "ImageObject",
                "url": "https://cdn.alaatv.com/upload/Alaa-logo.png?w=182&h=224"
              }
          },
          "datePublished" : "{{ $content->created_at }}",
          "dateModified" : "{{ $content->updated_at }}"
        }
    @endif
    </script>

@endsection

@section('pageBar')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <i class="fa fa-home m--padding-right-5"></i>
                <a class="m-link" href="{{route('web.index')}}">@lang('page.Home')</a>
            </li>
            <li class="breadcrumb-item">
                <i class="fa fa-video-camera m--padding-right-5"></i>
                <a class="m-link"
                   href="{{ action("Web\ContentController@index") }}">@lang('content.Educational Content Of Alaa')</a>
            </li>
            @if(isset($contentSetName))
                <li class="breadcrumb-item">
                    <i class="fa fa-video-camera m--padding-right-5"></i>
                    <a class="m-link" href="{{route('set.show' , ['set'=>$content->contentset_id])}}">{{ $contentSetName }}</a>
                </li>
            @endif
            <li class="breadcrumb-item active" aria-current="page">
                <a class="m-link" href="#"> {{ $content->displayName }} </a>
            </li>
        </ol>
    </nav>
    <input id="js-var-contentId" class="m--hide" type="hidden" value='{{ $content->id }}'>
    <input id="js-var-contentDName" class="m--hide" type="hidden" value='{{ $content->displayName }}'>
    <input id="js-var-contentUrl" class="m--hide" type="hidden"
           value='{{action("Web\ContentController@show" , $content)}}'>
    <input id="js-var-contentEmbedUrl" class="m--hide" type="hidden"
           value='{{action("Web\ContentController@embed" , $content)}}'>
@endsection

@section('content')

    <div class="row boxed">

        {{-- content video and other content of set --}}
        <div class="col-12">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-8 mx-auto top-right-section">
                    @if(!$user_can_see_content)
                        <div
                            class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert alert-info alert-dismissible fade show"
                            role="alert">
                            <div class="m-alert__icon">
                                <i class="fa fa-exclamation"></i>
                                <span></span>
                            </div>
                            <div class="m-alert__text">
                                <strong>{{ $message }}</strong>
                                @if($productsThatHaveThisContent->isNotEmpty())
                                    <button type="button"
                                            class="btn m-btn--air btn-warning btn-sm m-btn m-btn--pill m-btn--wide scrollToOwlCarouselParentProducts">
                                        مشاهده محصولات
                                    </button>
                                @endif
                            </div>
                            <div class="m-alert__close">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                            </div>
                        </div>
                    @endif
                    @if(isset($content->template))
                        <!--begin::Portlet-->
                        <div class="m-portlet">
                            @if(optional($content->template)->name == "video1")
                                <div class="m-portlet__body a--nuevo-alaa-theme a--media-parent">
                                    <div class="a--video-wraper">
                                        <video id="video-{{ $content->id }}"
                                               class="video-js vjs-fluid vjs-default-skin vjs-big-play-centered"
                                               preload="none"
                                               height="360"
                                               width="640"
                                               poster="{{ $content->thumbnail }}"
                                               controls
                                               webkit-playsinline="true"
                                               playsinline="true" >
                                            @if($user_can_see_content)
                                                @foreach($content->getVideos() as $source)
                                                    <source src="{{ $source->link }}" type='video/mp4' res="{{ $source->res }}"
                                                            @if(strcmp( $source->res,"240p") == 0)
                                                            default
                                                            @endif
                                                            label="{{ $source->caption }}"/>
                                                @endforeach
                                            @elseif($productsThatHaveThisContent->isNotEmpty())
                                                @foreach($productsThatHaveThisContent as $productKey=>$product)
                                                    @if($productKey === 0)
                                                        <source src="{{ $product->introVideo }}" type="video/mp4"/>
                                                    @endif
                                                @endforeach
                                            @endif
                                            <p class="vjs-no-js">@lang('content.javascript is disables! we need it to play a video')</p>
                                        </video>
                                    </div>
                                    <div class="m--clearfix"></div>
                                    <div class="m--margin-top-10">
                                        @if(isset($videosWithSameSet) and $videosWithSameSet->isNotEmpty())
                                            <nav aria-label="Page navigation" class="table-responsive">
                                                <ul class="pagination justify-content-center">
                                                    <li class="page-item">
                                                        <a class="page-link"
                                                           href="{{action("Web\ContentController@show" , $videosWithSameSet->first()["content"])}}"
                                                           aria-label="اولین">
                                                            <span aria-hidden="true">&laquo;</span>
                                                            <span class="sr-only">اولین</span>
                                                        </a>
                                                    </li>
                                                    @foreach($videosWithSameSetL->take(-5) as $item)

                                                        <li class="page-item @if($item["content"]->id == $content->id) active @endif">
                                                            <a class="page-link"
                                                               href="{{action("Web\ContentController@show" , $item["content"])}}">{{ $item["content"]->order }}</a>
                                                        </li>

                                                    @endforeach
                                                    @foreach($videosWithSameSetR->take(6) as $item)

                                                        <li class="page-item @if($item["content"]->id == $content->id) active @endif">
                                                            <a class="page-link"
                                                               href="{{action("Web\ContentController@show" , $item["content"])}}">{{ $item["content"]->order }}</a>
                                                        </li>

                                                    @endforeach
                                                    <li class="page-item">
                                                        <a class="page-link"
                                                           href="{{action("Web\ContentController@show" , $videosWithSameSet->last()["content"])}}"
                                                           aria-label="آخرین">
                                                            <span aria-hidden="true">&raquo;</span>
                                                            <span class="sr-only">آخرین</span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </nav>
                                        @endif
                                        @if($productsHasThisContentThroughBlockCollection->count() > 0)
                                            @foreach($productsHasThisContentThroughBlockCollection as $productKey=>$product)
                                                @if($product->type['type'] === 'simple')
                                                    <button
                                                        @include('partials.gtm-eec.product', ['position'=>$productKey, 'list'=>'نمونه فیلم-دکمه افزودن به سبد', 'quantity'=>'1'])
                                                        class="btn m-btn--air btn-success m-btn--icon m--margin-bottom-5 a--gtm-eec-product btnAddToCart"
                                                        data-pid="{{ $product->id }}">
                                                        <span>
                                                            <i class="fa fa-cart-arrow-down"></i>
                                                            <i class="fas fa-sync-alt fa-spin m--hide"></i>
                                                            <span>افزودن {{ $product->name }} به سبد خرید</span>
                                                        </span>
                                                    </button>
                                                @else

                                                    {{--                                            <a href="{{ $product->url }}" class="btn m-btn--pill m-btn--air m-btn m-btn--gradient-from-info m-btn--gradient-to-accent btnViewProductPage">--}}
                                                    {{--                                                مشاهده--}}
                                                    {{--                                                {{ $product->name }}--}}
                                                    {{--                                            </a>--}}

                                                @endif
                                            @endforeach
                                        @endif

                                        @if(!$user_can_see_content && $productsThatHaveThisContent->isNotEmpty())
                                            @foreach($productsThatHaveThisContent as $productKey=>$product)
                                                @if($product->type['type'] === 'simple')
                                                    <button
                                                        @include('partials.gtm-eec.product', ['position'=>$productKey, 'list'=>'محصولاتی که شامل این محتوا هستند-دکمه افزودن به سبد', 'quantity'=>'1'])
                                                        class="btn m-btn--air btn-success m-btn--icon m--margin-bottom-5 a--gtm-eec-product btnAddToCart"
                                                        data-pid="{{ $product->id }}">
                                                        <span>
                                                            <i class="fa fa-cart-arrow-down"></i>
                                                            <i class="fas fa-sync-alt fa-spin m--hide"></i>
                                                            <span>افزودن {{ $product->name }} به سبد خرید</span>
                                                        </span>
                                                    </button>
                                                @else

                                                    {{--                                            <a href="{{ $product->url }}" class="btn m-btn--pill m-btn--air m-btn m-btn--gradient-from-info m-btn--gradient-to-accent btnViewProductPage">--}}
                                                    {{--                                                مشاهده--}}
                                                    {{--                                                {{ $product->name }}--}}
                                                    {{--                                            </a>--}}

                                                @endif
                                            @endforeach
                                        @endif
                                    </div>
                                </div>
                            @elseif(optional($content->template)->name == "pamphlet1" )
                                <div class="m-portlet__body">
                                    <!--begin::m-widget5-->
                                    <div class="m-widget5">
                                        <div class="m-widget5__item">
                                            <div class="m-widget5__content">
                                                <div class="m-widget5__pic">
                                                    <img class="m-widget7__img img-fluid lazy-image" width="50"
                                                         data-src="/assets/app/media/img/files/pdf.svg" alt="pdf">
                                                </div>
                                                <div class="m-widget5__section">
                                                    <h4 class="m-widget5__title">
                                                        {{ $content->displayName  }}
                                                    </h4>
                                                    <div class="m-widget5__info">
                                                        @if($user_can_see_content)
                                                            <div class="btn-group m-btn-group" role="group" aria-label="...">
                                                                @foreach($content->getPamphlets() as $file)
                                                                    <a href="{{ $file->link }}" target="_blank"
                                                                       title="دانلود مستقیم">
                                                                        <button type="button" class="btn btn-primary">
                                                                            دانلود {{ $file->caption }}
                                                                        </button>
                                                                    </a>
                                                                @endforeach
                                                            </div>
                                                        @endif
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="m-widget5__content"></div>
                                        </div>
                                    </div>
                                    <!--end::m-widget5-->
                                    <div class="m-separator m-separator--space m-separator--dashed"></div>
                                    @if(!empty($tags))
                                        @include("partials.search.tagLabel" , ["tags"=>$tags])
                                    @endif
                                    <div class="m--margin-top-10">
                                        @if(isset($videosWithSameSet) and $videosWithSameSet->isNotEmpty())
                                            <nav aria-label="Page navigation" class="table-responsive">
                                                <ul class="pagination justify-content-center">
                                                    <li class="page-item">
                                                        <a class="page-link"
                                                           href="{{action("Web\ContentController@show" , $videosWithSameSet->first()["content"])}}"
                                                           aria-label="اولین">
                                                            <span aria-hidden="true">&laquo;</span>
                                                            <span class="sr-only">اولین</span>
                                                        </a>
                                                    </li>
                                                    @foreach($videosWithSameSetL->take(-5) as $item)

                                                        <li class="page-item @if($item["content"]->id == $content->id) active @endif">
                                                            <a class="page-link"
                                                               href="{{action("Web\ContentController@show" , $item["content"])}}">{{ $item["content"]->order }}</a>
                                                        </li>

                                                    @endforeach
                                                    @foreach($videosWithSameSetR->take(6) as $item)

                                                        <li class="page-item @if($item["content"]->id == $content->id) active @endif">
                                                            <a class="page-link"
                                                               href="{{action("Web\ContentController@show" , $item["content"])}}">{{ $item["content"]->order }}</a>
                                                        </li>

                                                    @endforeach
                                                    <li class="page-item">
                                                        <a class="page-link"
                                                           href="{{action("Web\ContentController@show" , $videosWithSameSet->last()["content"])}}"
                                                           aria-label="آخرین">
                                                            <span aria-hidden="true">&raquo;</span>
                                                            <span class="sr-only">آخرین</span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </nav>
                                        @endif
                                        @if($productsHasThisContentThroughBlockCollection->count() > 0)
                                            @foreach($productsHasThisContentThroughBlockCollection as $productKey=>$product)
                                                @if($product->type['type'] === 'simple')
                                                    <button
                                                        @include('partials.gtm-eec.product', ['position'=>$productKey, 'list'=>'نمونه فیلم-دکمه افزودن به سبد', 'quantity'=>'1'])
                                                        class="btn m-btn--air btn-success m-btn--icon m--margin-bottom-5 a--gtm-eec-product btnAddToCart"
                                                        data-pid="{{ $product->id }}">
                                                        <span>
                                                            <i class="fa fa-cart-arrow-down"></i>
                                                            <i class="fas fa-sync-alt fa-spin m--hide"></i>
                                                            <span>افزودن {{ $product->name }} به سبد خرید</span>
                                                        </span>
                                                    </button>
                                                @else

                                                    {{--                                            <a href="{{ $product->url }}" class="btn m-btn--pill m-btn--air m-btn m-btn--gradient-from-info m-btn--gradient-to-accent btnViewProductPage">--}}
                                                    {{--                                                مشاهده--}}
                                                    {{--                                                {{ $product->name }}--}}
                                                    {{--                                            </a>--}}

                                                @endif
                                            @endforeach
                                        @endif

                                        @if(!$user_can_see_content && $productsThatHaveThisContent->isNotEmpty())
                                            @foreach($productsThatHaveThisContent as $productKey=>$product)
                                                @if($product->type['type'] === 'simple')
                                                    <button
                                                        @include('partials.gtm-eec.product', ['position'=>$productKey, 'list'=>'محصولاتی که شامل این محتوا هستند-دکمه افزودن به سبد', 'quantity'=>'1'])
                                                        class="btn m-btn--air btn-success m-btn--icon m--margin-bottom-5 a--gtm-eec-product btnAddToCart"
                                                        data-pid="{{ $product->id }}">
                                                        <span>
                                                            <i class="fa fa-cart-arrow-down"></i>
                                                            <i class="fas fa-sync-alt fa-spin m--hide"></i>
                                                            <span>افزودن {{ $product->name }} به سبد خرید</span>
                                                        </span>
                                                    </button>
                                                @else

                                                    {{--                                            <a href="{{ $product->url }}" class="btn m-btn--pill m-btn--air m-btn m-btn--gradient-from-info m-btn--gradient-to-accent btnViewProductPage">--}}
                                                    {{--                                                مشاهده--}}
                                                    {{--                                                {{ $product->name }}--}}
                                                    {{--                                            </a>--}}

                                                @endif
                                            @endforeach
                                        @endif
                                    </div>


                                    <div class="row">
                                        <div class="col downloadLinkColumn">
                                            <div class="m-portlet m--full-height m-portlet--success m-portlet--head-solid-bg m-portlet--bordered" style="height: 500px;">
                                                @if(!$user_can_see_content)
                                                    <div class="blockedContent" data-toggle="m-tooltip" data-placement="top" data-original-title="این فایل یک محصول است و با خرید یکی از محصولات آن می توانید استفاده کنید.">
                                                        @if($productsThatHaveThisContent->isNotEmpty() && (!$user_can_see_content || ($content->isFree && false)) )
                                                            @foreach($productsThatHaveThisContent as $productKey=>$product)
                                                                <div class="ParentProductsItem"
                                                                     data-position="{{ $productKey }}"
                                                                    @include('partials.gtm-eec.product', ['position'=>$productKey, 'list'=>'محصولاتی که شامل این محتوا هستند']) >

                                                                    <div class="image">
                                                                        <a href="{{ $product->url }}"
                                                                           class="a--block-imageWrapper-image a--gtm-eec-product a--gtm-eec-product-click d-block"
                                                                            @include('partials.gtm-eec.product', ['position'=>$productKey, 'list'=>'محصولاتی که شامل این محتوا هستند'])>
                                                                            <img src="https://cdn.alaatv.com/loder.jpg?w=1&h=1"
                                                                                 data-src="{{ $product->photo }}" alt="{{ $product->name }}"
                                                                                 class="a--block-image lazy-image" width="400" height="400"/>
                                                                        </a>
                                                                    </div>
                                                                    <div class="title">
                                                                        <a href="{{ $product->url }}"
                                                                           class="m-link a--owl-carousel-type-2-item-subtitle a--gtm-eec-product-click"
                                                                            @include('partials.gtm-eec.product', ['position'=>$productKey, 'list'=>'محصولاتی که شامل این محتوا هستند'])>
                                                                            <span class="m-badge m-badge--danger m-badge--dot"></span>
                                                                            {{ $product->name }}
                                                                        </a>
                                                                    </div>
                                                                </div>
                                                            @endforeach
                                                        @endif
                                                    </div>
                                                @endif
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            @elseif(optional($content->template)->name == "article1")
                                <div class="m-portlet__head">
                                    <div class="m-portlet__head-caption">
                                        <div class="m-portlet__head-title">
                                            <h1 class="m-portlet__head-text">
                                                {{$content->name}}
                                            </h1>
                                        </div>
                                    </div>
                                </div>
                                <div class="m-portlet__body">
                                    <div class="m-portlet__body-progress">Loading</div>
                                    <div>
                                        {!! $content->context !!}
                                    </div>
                                    <div class="m-separator m-separator--space m-separator--dashed"></div>
                                    @if(!empty($tags))
                                        @include("partials.search.tagLabel" , ["tags"=>$tags])
                                    @endif
                                </div>
                            @endif
                        </div>
                        <!--end::Portlet-->
                    @else
                        <div class="alert alert-danger" role="alert">
                            <strong>خطا!</strong> خطا لطفا لینک این صفحه را برای ما ارسال کنید تا بررسی شود.
                        </div>
                    @endif
                </div>
                @if(isset($videosWithSameSet) and $videosWithSameSet->count() > 0)
                    <div class="col-12 col-sm-12 col-md-12 col-lg-4 top-left-section">
                        <!--begin::Portlet-->
                        <div class="m-portlet">
                            <div class="m-portlet__head">
                                <div class="m-portlet__head-caption">
                                    <div class="m-portlet__head-title">
                                        <h3 class="m-portlet__head-text">
                                            فیلم ها
                                            @if(isset($contentSetName))
                                                <small>
                                                    {{ $contentSetName }}
                                                </small>
                                            @endif
                                        </h3>
                                    </div>
                                </div>
                            </div>
                            <div class="m-portlet__body m--padding-10">
                                <div id="playListScroller"
                                     class="m-scrollable11 AlaaScroll"
                                     data-scrollable="true"
                                     {{--                             data-height="{{ min($videosWithSameSet->count(),(optional($content->template)->name == "video1" ?  11 : 4)) * 103 }}"--}}
                                     data-height="360"
                                     data-scrollbar-shown="true">
                                    <div class="m-portlet__body-progress">Loading</div>

                                    <!--begin::m-widget5-->
                                    <div class="a-widget5">
                                        @foreach($videosWithSameSet as $item)
                                            <div class="a-widget5__item" id="playlistItem_{{ $item["content"]->id }}">
                                                <div
                                                    class="a-widget5__content {{ $item["content"]->id == $content->id ? 'm--bg-info' : '' }}">
                                                    <div class="a-widget5__pic">
                                                        <a class="m-link a--full-width"
                                                           href="{{action("Web\ContentController@show" , $item["content"])}}">
                                                            <img class="m-widget7__img a--full-width lazy-image"
                                                                 width="170" height="96"
                                                                 src="https://cdn.alaatv.com/loder.jpg?w=1&h=1"
                                                                 data-src="{{ isset($item["thumbnail"]) ? $item["thumbnail"]."?w=210&h=118":'' }}"
                                                                 alt="{{ $item["content"]->name }}">
                                                        </a>
                                                    </div>
                                                    <div class="a-widget5__section">
                                                        <h4 class="a-widget5__title">
                                                            <a class="m-link"
                                                               href="{{action("Web\ContentController@show" , $item["content"])}}"
                                                               data-toggle="m-tooltip" title="{{ $item["content"]->display_name }}" data-placement="top" >
                                                                {!! str_limit($item["content"]->display_name, 45, ' ...') !!}
                                                            </a>
                                                        </h4>
                                                        <div class="a-widget5__info">
                                                            <div class="content-description">
                                                                {!! str_limit(clearHtml($item["content"]->description), 100, ' ...') !!}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                        @endforeach
                                    </div>
                                    <!--end::m-widget5-->

                                </div>
                            </div>
                        </div>
                        <!--end::Portlet-->

                        <div class="top-left-section-ad">
                            @include('partials.ads.list', ['id'=>'contentShowPage-leftSide-1'])
                        </div>

                    </div>
                @endif
            </div>
        </div>

        {{-- ad banner and related items --}}
        <div class="col-12">

            @include('partials.ads.list', ['id'=>'contentShowPage-rightSide-0'])

            @if($hasRecommendedBlock)
                @include('partials.widgets.ScollCarousel.body', [
                    'title'=> 'موارد مرتبط',
                    'customClass'=> 'RelatedItems',
                    'squareSing'=> 'recomender',
                    'puls'=> true,
                    'sort'=> true,
                    'scrollCarouselItems'=> view('content.partials.recommendedItemRecognizer', [
                        'recommendedItems'=>$recommendedItems,
                        'gtmEecList'=>'موارد مرتبط',
                        'sort'=> true,
                        'responsiveClass'=>''
                    ]),
                ])
            @endif

        </div>

        {{-- description and pamphlets and video download link and sources --}}
        <div class="col-12 m--margin-top-15 m--margin-bottom-15">
            <div class="row">

                {{-- description and pamphlets and sources --}}
                <div class="col-md-8 mx-auto detailesColumn">
                    <!--begin::Portlet-->
                    <div class="m-portlet m--full-height">
                        <div class="m-portlet__body contentDetailesWrapper a--nuevo-alaa-theme">

                            <h1 class="m--regular-font-size-lg3 m--font-bold m--font-focus contentTitleH1">{{ $content->displayName }}</h1>

                            @include('partials.favorite', [
                                'favActionUrl' => route('web.mark.favorite.content', [ 'c' => $content->id ]),
                                'unfavActionUrl' => route('web.mark.unfavorite.content', [ 'c' => $content->id ]),
                                'isFavored' => $isFavored
                            ])

                            <ul class="nav nav-tabs" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" data-toggle="tab" href="#" data-target="#m_tabs_1_1">توضیحات</a>
                                </li>
                                @if($pamphletsWithSameSet->count() > 0 and $pamphletsWithSameSet->where("content.id" , "<>",$content->id)->isNotEmpty())
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#m_tabs_1_2">جزوات</a>
                                    </li>
                                @endif
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active AlaaScroll" id="m_tabs_1_1" role="tabpanel">

                                    <div class="sources">
                                        @foreach($sources as $source)
                                            <div class="sources-item">
                                                <div class="sources-image">
                                                    <a href="{{$source->link}}" class="m-link">
                                                        <img class=""
                                                             src="{{$source->photo}}"
                                                             alt="{{ $source->title }}">
                                                    </a>
                                                </div>
                                                <div class="sources-title">
                                                    <a href="{{$source->link}}" class="m-link">
                                                        منبع: {{$source->title}}
                                                    </a>
                                                </div>
                                            </div>
                                        @endforeach
                                    </div>


                                    @if(isset($content->template))

                                        @if(optional($content->template)->name == "video1")
                                            @if(isset($content->author_id))
                                                <div class="m-widget3">
                                                    <div class="m-widget3__item">
                                                        <div class="m-widget3__header">
                                                            <div class="m-widget3__user-img">
                                                                <img class="m-widget3__img lazy-image"
                                                                     data-src="{{ $content->author->photo }}"
                                                                     alt="{{ $author }}"
                                                                     width="1"
                                                                     height="1">
                                                            </div>
                                                            <div class="m-widget3__info">
                                                    <span class="m-widget3__username">
                                                    {{ $author }}
                                                    </span>
                                                                @if(isset($contentSetName))
                                                                    <br>
                                                                    <h3 class="m-widget3__time m--font-info">
                                                                        <a href="{{route('set.show' , ['set'=>$content->contentset_id])}}">{{ $contentSetName }}</a>
                                                                    </h3>
                                                                @endif
                                                            </div>
                                                            @if($userCanSeeCounter)
                                                                <span class="m-widget3__status m--font-info m--block-inline">
                                                        <i class="fa fa-eye"> {{ $seenCount }}</i>
                                                    </span>
                                                            @endif
                                                        </div>
                                                        <div class="m-widget3__body">
                                                            <div class="m-widget3__text">

{{--                                                                @if(strlen($content->description) > 2000)--}}
{{--                                                                    <div class="a--summarize-text">--}}
{{--                                                                        <div class="a--summarize-text-toggleBtn">--}}
{{--                                                                            <button--}}
{{--                                                                                class="btn btn-accent m-btn m-btn--icon m-btn--icon-only m-btn--custom m-btn--pill">--}}
{{--                                                                                <i class="fa fa-angle-double-down"></i>--}}
{{--                                                                            </button>--}}
{{--                                                                        </div>--}}
{{--                                                                        <div class="a--summarize-text-content">--}}
{{--                                                                            {!! $content->description !!}--}}
{{--                                                                        </div>--}}
{{--                                                                    </div>--}}
{{--                                                                @else--}}
                                                                    {!! $content->description !!}
{{--                                                                @endif--}}

                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="m-separator m-separator--space m-separator--dashed"></div>
                                            @endif
                                            <div class="m-separator m-separator--space m-separator--dashed"></div>
                                            @if(!empty($tags))
                                                @include("partials.search.tagLabel" , ["tags"=>$tags])
                                            @endif
                                        @elseif(optional($content->template)->name == "pamphlet1" )
                                            @if(isset($content->description[0]))
{{--                                                @if(strlen($content->description) > 2000)--}}
{{--                                                    <div class="a--summarize-text">--}}
{{--                                                        <div class="a--summarize-text-toggleBtn">--}}
{{--                                                            <button--}}
{{--                                                                class="btn btn-accent m-btn m-btn--icon m-btn--icon-only m-btn--custom m-btn--pill">--}}
{{--                                                                <i class="fa fa-angle-double-down"></i>--}}
{{--                                                            </button>--}}
{{--                                                        </div>--}}
{{--                                                        <div class="a--summarize-text-content">--}}
{{--                                                            {!! $content->description !!}--}}
{{--                                                        </div>--}}
{{--                                                    </div>--}}
{{--                                                @else--}}
                                                    {!! $content->description !!}
{{--                                                @endif--}}
                                            @endif
                                        @elseif(optional($content->template)->name == "article1")

                                        @endif
                                    @else

                                    @endif

                                </div>
                                <div class="tab-pane a--list2 AlaaScroll m--padding-right-10" id="m_tabs_1_2" role="tabpanel">
                                    @if($pamphletsWithSameSet->count() > 0 and $pamphletsWithSameSet->where("content.id" , "<>",$content->id)->isNotEmpty())
                                        @foreach($pamphletsWithSameSet as  $item)
                                            <div class="a--list2-item">
                                                <div class="a--list2-thumbnail">
                                                    <a href="{{ action("Web\ContentController@show" , $item["content"]) }}">
                                                        <svg width="50" height="50" viewBox="-79 0 512 512" xmlns="http://www.w3.org/2000/svg">' +
                                                            <path d="m353.101562 485.515625h-353.101562v-485.515625h273.65625l79.445312 79.449219zm0 0" fill="#e3e4d8"/>
                                                            <path d="m273.65625 0v79.449219h79.445312zm0 0" fill="#d0cebd"/>
                                                            <path d="m0 353.101562h353.101562v158.898438h-353.101562zm0 0" fill="#b53438"/>
                                                            <g fill="#fff">
                                                                <path d="m52.964844 485.515625c-4.871094 0-8.828125-3.953125-8.828125-8.824219v-88.277344c0-4.875 3.957031-8.828124 8.828125-8.828124 4.875 0 8.828125 3.953124 8.828125 8.828124v88.277344c0 4.871094-3.953125 8.824219-8.828125 8.824219zm0 0"/>
                                                                <path d="m300.136719 397.242188h-52.964844c-4.871094 0-8.828125-3.957032-8.828125-8.828126 0-4.875 3.957031-8.828124 8.828125-8.828124h52.964844c4.875 0 8.828125 3.953124 8.828125 8.828124 0 4.871094-3.953125 8.828126-8.828125 8.828126zm0 0"/>
                                                                <path d="m300.136719 441.378906h-52.964844c-4.871094 0-8.828125-3.953125-8.828125-8.828125 0-4.871093 3.957031-8.828125 8.828125-8.828125h52.964844c4.875 0 8.828125 3.957032 8.828125 8.828125 0 4.875-3.953125 8.828125-8.828125 8.828125zm0 0"/>
                                                                <path d="m247.171875 485.515625c-4.871094 0-8.828125-3.953125-8.828125-8.824219v-88.277344c0-4.875 3.957031-8.828124 8.828125-8.828124 4.875 0 8.828125 3.953124 8.828125 8.828124v88.277344c0 4.871094-3.953125 8.824219-8.828125 8.824219zm0 0"/>
                                                            </g>
                                                            <path d="m170.203125 95.136719c-.863281.28125-11.695313 15.261719.847656 27.9375 8.351563-18.371094-.464843-28.054688-.847656-27.9375m5.34375 73.523437c-6.296875 21.496094-14.601563 44.703125-23.527344 65.710938 18.378907-7.042969 38.375-13.195313 57.140625-17.546875-11.871094-13.621094-23.738281-30.632813-33.613281-48.164063m65.710937 57.175782c7.167969 5.445312 8.914063 8.199218 13.613282 8.199218 2.054687 0 7.925781-.085937 10.636718-3.828125 1.316407-1.820312 1.828126-2.984375 2.019532-3.59375-1.074219-.574219-2.515625-1.710937-10.335938-1.710937-4.449218 0-10.027344.191406-15.933594.933594m-119.957031 38.601562c-18.804687 10.425781-26.464843 19-27.011719 23.835938-.089843.804687-.328124 2.90625 3.785157 6.011718 1.316406-.414062 8.96875-3.859375 23.226562-29.847656m-23.421875 44.527344c-3.0625 0-6-.980469-8.507812-2.832032-9.15625-6.796874-10.390625-14.347656-9.808594-19.492187 1.597656-14.132813 19.304688-28.945313 52.648438-44.03125 13.230468-28.636719 25.820312-63.921875 33.324218-93.398437-8.773437-18.871094-17.3125-43.351563-11.097656-57.714844 2.179688-5.03125 4.910156-8.894532 9.976562-10.566406 2.011719-.652344 7.078126-1.480469 8.941407-1.480469 4.617187 0 9.050781 5.507812 11.183593 9.089843 3.972657 6.648438 3.992188 14.390626 3.363282 21.859376-.609375 7.253906-1.84375 14.46875-3.265625 21.601562-1.039063 5.242188-2.214844 10.460938-3.46875 15.660156 11.855469 24.175782 28.644531 48.816406 44.746093 65.683594 11.539063-2.054688 21.460938-3.097656 29.546876-3.097656 13.761718 0 22.121093 3.167968 25.519531 9.691406 2.828125 5.402344 1.660156 11.726562-3.433594 18.769531-4.898437 6.769531-11.640625 10.34375-19.523437 10.34375-10.710938 0-23.15625-6.671875-37.050782-19.851562-24.957031 5.15625-54.097656 14.34375-77.65625 24.515625-7.355468 15.410156-14.398437 27.824218-20.964844 36.933594-8.996093 12.5-16.773437 18.316406-24.472656 18.316406" fill="#b53438"/>
                                                            <path d="m79.449219 450.207031h-26.484375c-4.871094 0-8.828125-3.953125-8.828125-8.828125v-52.964844c0-4.875 3.957031-8.828124 8.828125-8.828124h26.484375c19.472656 0 35.308593 15.835937 35.308593 35.3125 0 19.472656-15.835937 35.308593-35.308593 35.308593zm-17.65625-17.65625h17.65625c9.734375 0 17.652343-7.917969 17.652343-17.652343 0-9.738282-7.917968-17.65625-17.652343-17.65625h-17.65625zm0 0" fill="#fff"/>
                                                            <path d="m158.898438 485.515625h-8.828126c-4.875 0-8.828124-3.953125-8.828124-8.824219v-88.277344c0-4.875 3.953124-8.828124 8.828124-8.828124h8.828126c29.199218 0 52.964843 23.753906 52.964843 52.964843 0 29.210938-23.765625 52.964844-52.964843 52.964844zm0-17.652344h.085937zm0-70.621093v70.621093c19.472656 0 35.308593-15.839843 35.308593-35.3125 0-19.472656-15.835937-35.308593-35.308593-35.308593zm0 0" fill="#fff"/>
                                                        </svg>
                                                    </a>
                                                </div>
                                                <div class="a--list2-content">
                                                    <h2 class="a--list2-title">
                                                        <a href="{{ action("Web\ContentController@show" , $item["content"]) }}">{{ $item["content"]->name }}</a>
                                                    </h2>
                                                    <div class="a--list2-info"></div>
                                                    <div class="a--list2-desc"></div>
                                                </div>
                                                <div class="a--list2-action">
                                                    <a href="{{ action("Web\ContentController@show" , $item["content"]) }}" class="downloadPamphletIcon">
                                                        <i class="fa fa-cloud-download-alt"></i>
                                                    </a>
                                                </div>
                                            </div>
                                        @endforeach
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--end::Portlet-->
                </div>

                {{-- video download link and products That Have This Content--}}
                @if(isset($content->template) && optional($content->template)->name == "video1")
                    <div class="col-md-4 downloadLinkColumn">
                        <div class="m-portlet m--full-height m-portlet--success m-portlet--head-solid-bg m-portlet--bordered">

                            @if(!$user_can_see_content)
                                <div class="blockedContent" data-toggle="m-tooltip" data-placement="top" data-original-title="این فایل یک محصول است و با خرید یکی از محصولات آن می توانید استفاده کنید.">
                                    @if($productsThatHaveThisContent->isNotEmpty() && (!$user_can_see_content || ($content->isFree && false)) )
                                        @foreach($productsThatHaveThisContent as $productKey=>$product)
                                            <div class="ParentProductsItem"
                                                 data-position="{{ $productKey }}"
                                                @include('partials.gtm-eec.product', ['position'=>$productKey, 'list'=>'محصولاتی که شامل این محتوا هستند']) >

                                                <div class="image">
                                                    <a href="{{ $product->url }}"
                                                       class="a--block-imageWrapper-image a--gtm-eec-product a--gtm-eec-product-click d-block"
                                                        @include('partials.gtm-eec.product', ['position'=>$productKey, 'list'=>'محصولاتی که شامل این محتوا هستند'])>
                                                        <img src="https://cdn.alaatv.com/loder.jpg?w=1&h=1"
                                                             data-src="{{ $product->photo }}" alt="{{ $product->name }}"
                                                             class="a--block-image lazy-image" width="400" height="400"/>
                                                    </a>
                                                </div>
                                                <div class="title">
                                                    <a href="{{ $product->url }}"
                                                       class="m-link a--owl-carousel-type-2-item-subtitle a--gtm-eec-product-click"
                                                        @include('partials.gtm-eec.product', ['position'=>$productKey, 'list'=>'محصولاتی که شامل این محتوا هستند'])>
                                                        <span class="m-badge m-badge--danger m-badge--dot"></span>
                                                        {{ $product->name }}
                                                    </a>
                                                </div>
                                            </div>
                                        @endforeach
                                    @endif
                                </div>
                            @endif

                            <div class="m-portlet__head">
                                <div class="m-portlet__head-caption">
                                    <div class="m-portlet__head-title">
                                        <span class="m-portlet__head-icon">
                                            <i class="flaticon-placeholder-2"></i>
                                        </span>
                                        <h3 class="m-portlet__head-text">
                                            لینک های مستقیم دانلود این فیلم
                                        </h3>
                                    </div>
                                </div>
                                <div class="m-portlet__head-tools"></div>
                            </div>

                            <div class="m-portlet__body">
                                <div class="row">
                                    @if(isset($content->file) and $content->file->isNotEmpty())
                                        <div class="col-12 text-justify">
                                            <p>
                                                با IDM یا ADM و یا wget دانلود کنید.
                                            </p>
                                        @foreach($content->file->get('video') as $file)
                                                <div class="m-alert m-alert--icon m-alert--outline alert alert-success" role="alert">
                                                    <div class="m-alert__text text-left">
                                                        <strong>
                                                            <a
                                                                @if(true)
                                                                href="{{ ($user_can_see_content) ? $file->link . '?download=1' : '#' }}"
                                                                class="m-link"
                                                                @else
                                                                data-href="{{ Request::url() }}"
                                                                class="m-link LoginBeforeClick"
                                                                @endif>
                                                                دانلود فایل {{$file->caption}}
                                                            </a>
                                                        </strong>
                                                    </div>
                                                    <a
                                                        @if(true)
                                                        href="{{ ($user_can_see_content) ? $file->link . '?download=1' : '#' }}"
                                                        @else
                                                        data-href="{{ Request::url() }}"
                                                        class="LoginBeforeClick"
                                                        @endif>

                                                        @if(isset($file->res))
                                                            <span class="m-badge m-badge--warning m-badge--wide m-badge--rounded">
                                                                {{ $file->res }}
                                                            </span>
                                                        @endif
                                                        @if(isset($file->ext))
                                                            <span class="m-badge m-badge--info m-badge--wide m-badge--rounded">
                                                                {{ $file->ext }}
                                                            </span>
                                                        @endif
                                                        @if(isset($file->size[0]))
                                                            حجم:
                                                            ({{ $file->size }})
                                                        @endif

                                                        <button type="button" class="btn btn-success btn-sm m-btn m-btn--pill m-btn--wide">
                                                            <i class="fa fa-download"></i>
                                                        </button>
                                                    </a>
                                                </div>
                                            @endforeach
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                @endif

            </div>
        </div>

        {{-- godar block--}}
        <div class="col">
            @foreach($contentBlocks as $block)
                @include('block.partials.main', [
                'blockCustomClass'=> 'contentBlock',
                'blockCustomId'=>'sectionId-'.$block->class,
                'blockType'=>(isset($block->sets) && $block->sets->count()>0)?'set':(isset($block->products) && $block->products->count()>0?'product':'content'),
                'blockUrlDisable'=>false,
                'btnLoadMore'=>true
                ])
            @endforeach
        </div>

        {{-- chibekhoonam --}}
        @if($content->isFree)
            <div class="col-12">
                <div class="AlaaAdDom" alaa-ad-preloadimage="1"></div>
            </div>
        @endif

    </div>

@endsection

@section('page-js')
    <script type="text/javascript" defer>
        var related_videos = [
            @if(!is_null(min(13,$videosWithSameSet->count())))
            @foreach($videosWithSameSet->random( min(13,$videosWithSameSet->count())) as $item)
            @if($item["content"]->id != $content->id)
            {!!
                json_encode([
                    'thumb' => (isset($item["thumbnail"]))?$item["thumbnail"]:"",
                    'url' => action("Web\ContentController@show" , $item["content"]),
                    'title' => ($item["content"]->display_name),
                    'duration' => '20:00'
                ])
            !!},
            @endif
            @endforeach
            @endif
        ];

        (function (w, d, i) {
            var fp = 'https://ads.alaatv.com/js/engine.js',
                l = 'AlaaAdEngine',
                s = 'script',
                da = new Date(),
                v = ''.concat(da.getFullYear(), (da.getMonth() + 1), da.getDate(), da.getHours()),
                f = d.getElementsByTagName(s)[0],
                j = d.createElement(s);
            w[l] = w[l] || {};
            w[l].UUID = i;
            j.async = true;
            j.src = fp + '?uuid=' + i + '&v=' + v;
            f.parentNode.insertBefore(j, f);
        })(window, document, '35b39d4b-517b-44bc-85c4-44f93242836f');

        var vastData = [
            {
            startAfter: 0,
            canSkipAfter: 5,
            mediaFiles: [
                {
                    id: '',
                    type: 'video/mp4',
                    label: 'خوب',
                    res: '1080p',
                    width: '1280',
                    height: '720',
                    default: true,
                    src: 'http://localhost/acm/videojs/videos/VAST-4.0-Short-Intro.mp4',
                }
                ,
                {
                    id: '',
                    type: 'video/mp4',
                    label: 'معمولی',
                    res: '720p',
                    width: '854',
                    height: '480',
                    src: 'http://localhost/acm/videojs/videos/VAST-4.0-Short-Intro-mid-resolution.mp4',
                },
                {
                    id: '',
                    type: 'video/mp4',
                    label: 'کم',
                    res: '240p',
                    width: '640',
                    height: '360',
                    src: 'http://localhost/acm/videojs/videos/VAST-4.0-Short-Intro-low-resolution.mp4',
                }
            ],
            ClickThrough: {
                attr: {
                    id: '',
                },
                val: 'http://localhost/shop'
            }
        },
            {
            startAfter: 10,
            canSkipAfter: 8,
            mediaFiles: [
                {
                    id: '',
                    type: 'video/mp4',
                    width: '1280',
                    height: '720',
                    src: 'http://localhost/acm/videojs/videos/VAST-4.0-Short-Intro.mp4',
                }
            ],
            ClickThrough: {
                attr: {
                    id: '',
                },
                val: ''
            }
        }
        ];

        vastData = [];

        var vastXml = '{{($hasRecommendedBlock)?route("web.vast.xml"):""}}';
    </script>
    <script src="{{ mix('/js/content-show.js') }}" type="text/javascript"></script>
@endsection

