@extends('partials.templatePage')

@section('page-css')
    <link href="{{ mix('/css/product-show.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('/acm/AlaatvCustomFiles/css/page/product/previewSetsOfProduct.css') }}" rel="stylesheet" type="text/css"/>
    <style>
        @if(
            (
                is_null(optional(optional(optional($block)->sets)->first())->getActiveContents2()) ||
                $block->sets->first()->getActiveContents2()->count() === 0
            ) &&
            (
                is_null(optional($block)->getActiveContent()) ||
                $block->getActiveContent()->count() === 0
            )
        )
            .productInfoNav-sampleVideo {
            display: none !important;
        }
        @endif
        @if(!isset($product->samplePhotos) || $product->samplePhotos->count() === 0)
            .productInfoNav-samplePamphlet {
            display: none !important;
        }
        @endif

        @if(
            mb_strlen(trim(strip_tags($product->shortDescription))) === 0 &&
            mb_strlen(trim(strip_tags($product->longDescription))) === 0
        )
            .productInfoNav-detailes {
            display: none !important;
        }
        @endif
        @if($liveDescriptions->isEmpty())
        .productInfoNav-liveDescription {
            display: none !important;
        }
        @endif
        @if(!isset($block) || !isset($block->products) || $block->products->count() === 0)
            .productInfoNav-relatedProduct {
            display: none !important;
        }
        @endif
    </style>
@endsection

@section('page-head')
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    {
        "@context" : "http://schema.org",
        "@type" : "Product",
        "name" : " {{ $product->name }}",
        "image" : "{{ $product->photo }}?w=400&h=400",
        "sku": "{{ $product->id }}",
        "brand" : {
            "@type" : "Brand",

            "name" : "آلاء",
            "logo": {
                "@type": "ImageObject",
                "url": "https://cdn.alaatv.com/upload/Alaa-logo.png?w=182&h=224"
              }
        },
        "offers" : {
            "@type" : "Offer",
            "price" : "{{ $product->price['final'] }}",
            "priceCurrency" : "IRR",
            "url" : "{{ $product->url }}",
            "availability": "https://schema.org/InStock",
            "itemCondition": "https://schema.org/NewCondition"
        }
    }

    </script>
@endsection

@section('pageBar')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <i class="fa fa-home m--padding-right-5"></i>
                <a class="m-link" href="{{route('web.index')}}">@lang('page.Home')</a>
            </li>
            <li class="breadcrumb-item">
                <i class="fa fa-chalkboard-teacher"></i>
                <a class="m-link" href="{{ action("Web\ShopPageController") }}">محصولات آموزشی</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                <a class="m-link" href="#"> {{ $product->name }} </a>
            </li>
        </ol>
    </nav>
@endsection

@section('content')


    <?php

    $allChildrenSets = $allChildrenSets->map(function ($object) {
        foreach ($object['sets'] as $key=>$item) {
            $object['sets'][$key] = (object)['id' => $key, 'name' => $item];
        }
        return $object;
    });

    ?>

    @if(in_array($product->type['id'] ,[config("constants.PRODUCT_TYPE_SIMPLE")]))
        @include('product.partials.showPage-topSection-simple')
    @elseif(in_array($product->type['id'], [config("constants.PRODUCT_TYPE_CONFIGURABLE"), config("constants.PRODUCT_TYPE_SELECTABLE")]))
        @include('product.partials.showPage-topSection-selectable')
    @endif

    {{-- پیش نمایش ست ها --}}
    @include('product.partials.previewSetsOfProduct', ['sets'=> $allChildrenSets->first()['sets'], 'products'=> $allChildrenSets])

    {{--نمونه فیلم--}}
    @include('block.partials.main', [
        'blockTitle'=>view('product.partials.productInfoNav', ['targetId'=>'sampleVideo' , 'product'=>$product , 'isForcedGift'=>$isForcedGift]),
        'blockUrlDisable'=>true,
        'blockType'=>'productSampleVideo',
        'imageDimension'=>'?w=300&h=169',
        'squareSing'=>false,
        'blockCustomClass'=>'a--owl-carousel-type-2 productShowBlock sampleVideo a--block-widget-1',
        'blockCustomId'=>'Block-sampleVideo',
        'btnLoadMore'=>true
        ])

    {{--نمونه جزوه--}}
    @include('product.partials.pamphlet')

    {{--  بررسی محصول  --}}
    @if(mb_strlen(trim(strip_tags($product->shortDescription))) > 0 || mb_strlen(trim(strip_tags($product->longDescription))) > 0)
        <div class="row m--margin-top-10">
            <div class="col m--margin-bottom-25">
                <div class="m-portlet m-portlet--tabs productDetailes boxed" id="productDetailes">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <h3 class="m-portlet__head-text">
                                    @include('product.partials.productInfoNav', ['targetId'=>'productDetailes'])
                                </h3>
                            </div>
                        </div>
                        <div class="m-portlet__head-tools">
                            <ul class="m-portlet__nav">
                                <li class="m-portlet__nav-item">
                                    <p class="m-portlet__nav-link m-portlet__nav-link--icon">


                                        @if($hasUserPurchasedProduct)
                                            <a class="btn m-btn m-btn--pill m-btn--air btn-info animated infinite pulse" role="button" href="{{ action("Web\UserController@userProductFiles") }}">
                                                <i class="fa fa-play-circle"></i>
                                                <span class="d-none d-sm-none d-md-inline-block d-lg-inline-block">
                                                    مشاهده در صفحه فیلم ها و جزوه های من
                                                </span>
                                            </a>
                                        @else
{{--                                            <button class="btn m-btn--air btn-success m-btn--icon btnAddToCart gta-track-add-to-card">--}}
{{--                                                <span>--}}
{{--                                                    <i class="fa fa-cart-arrow-down"></i>--}}
{{--                                                    <i class="fas fa-sync-alt fa-spin m--hide"></i>--}}
{{--                                                    <span>افزودن به سبد خرید</span>--}}
{{--                                                </span>--}}
{{--                                            </button>--}}
                                        @endif


                                    </p>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="m-portlet__body">
                        <div class="tab-content">
                            <div class="tab-pane active show" id="productInformation">
                                {!! $product->shortDescription !!}
                                @if( isset($product->longDescription) && strlen($product->longDescription) > 0 )
                                    <div>
                                        {!! $product->longDescription !!}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endif

    {{--  توضیحات لحظه ای  --}}
    @if($liveDescriptions->isNotEmpty())
        <div class="row m--margin-top-10">
            <div class="col m--margin-bottom-25">
                <div class="m-portlet m-portlet--tabs productLiveDescription" id="productLiveDescription">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <h3 class="m-portlet__head-text">
                                    @include('product.partials.productInfoNav', ['targetId'=>'productLiveDescription'])
                                </h3>
                            </div>
                        </div>
                    </div>
                    <div class="m-portlet__body">
                        <div class="tab-content">
                            <div class="m-timeline-3">
                                <div class="m-timeline-3__items">
                                    @foreach($liveDescriptions as $liveDescription)
                                        <div class="m-timeline-3__item m-timeline-3__item--info">
                                            <span class="m-timeline-3__item-time">{{$liveDescription->CreatedAt_Jalali_WithTime()}}</span>
                                            <div class="m-timeline-3__item-desc">
                                            <span class="m-timeline-3__item-user-name">
                                                <a  class="m-timeline-3__item-link">
                                                    {{$liveDescription->title}}
                                                </a>
                                            </span>
                                                <br>
                                                <span class="m-timeline-3__item-text">
                                                    {!!  $liveDescription->description !!}
                                            </span>

                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endif

    {{--  محصولات مرتبط  --}}
    @include('block.partials.main', [
        'blockTitle'=>view('product.partials.productInfoNav', ['targetId'=>'relatedProduct', 'product'=>$product , 'isForcedGift'=>$isForcedGift]),
        'blockUrlDisable'=>true,
        'blockType'=>'product',
        'squareSing'=>false,
        'blockCustomClass'=>'a--owl-carousel-type-2 productShowBlock relatedProduct',
        'blockCustomId'=>'Block-relatedProduct',
        'btnLoadMore'=>true
        ])

    {{--دکمه افزودن به سبد خرید موبایل --}}
    @include('product.partials.btnAddToCartForMobileDevice')

@endsection

@section('page-js')
    <script>
        var TotalQuantityAddedToCart = 0;
        var parentProduct = {
            id : '{{ $product->id }}',
            name : '{{ $product->name }}',
            price : '{{ number_format($product->price['final'], 2, '.', '') }}',
            brand: 'آلاء',
            category : '-',
            variant : '{{ $product->type['hint'] }}',
            quantity: 1
        };
        var parentProductTags = '{{ ($product->tags !== null) ? implode(',',optional($product->tags)->tags) : '-' }}';
        var allProductsSets = {!! json_encode($allChildrenSets) !!};
    </script>
    <script>
        var TotalQuantityAddedToCart = 0;
        var allSetsOfRaheAbrisham = [ { name: 'فرسنگ هفتم راه ابریشم (ریاضیات جامع تجربی) (ویژۀ 12 بهمن تا 2 اسفند 98) محمد صادق ثابتی', setId: 650 }, { name: 'فرسنگ ششم راه ابریشم (ریاضیات جامع تجربی) (ویژۀ 28 دی تا 11 بهمن 98) محمد صادق ثابتی', setId: 648 }, { name: 'همایش ریاضی تجربی گدار (نظام آموزشی جدید) (99-1398) محمد صادق ثابتی', setId: 747 }, { name: 'فرسنگ پنجم راه ابریشم (ریاضیات جامع تجربی) (ویژۀ 23 آذر تا 27 دی 98) محمد صادق ثابتی', setId: 646 }, { name: 'فرسنگ چهارم راه ابریشم (ریاضیات جامع تجربی) (ویژۀ 2 تا 22 آذر 98) محمد صادق ثابتی', setId: 644 }, { name: 'فرسنگ سوم راه ابریشم (ریاضیات جامع تجربی) (ویژۀ 11 آبان تا 1 آذر 98) محمد صادق ثابتی', setId: 643 }, { name: 'فرسنگ دوم راه ابریشم (ریاضیات جامع تجربی) (ویژۀ 20 مهر تا 10 آبان 98) محمد صادق ثابتی', setId: 642 }, { name: 'فرسنگ اول راه ابریشم (ریاضیات جامع تجربی) (ویژۀ 7 تا 19 مهر 98) محمد صادق ثابتی', setId: 617 }, { name: 'صفر تا صد ریاضی تجربی کنکور (نظام آموزشی جدید) (98-1397) محمد صادق ثابتی', setId: 217 }, { name: 'پیله راه ابریشم (ریاضیات مقدماتی) (نظام آموزشی جدید) (99-1398) محمد صادق ثابتی', setId: 604 }, { name: 'بارانداز راه ابریشم ( پس آزمون)', setId: 665 }, { name: 'پیش آزمون قلمچی راه ابریشم (نظام آموزشی جدید) (99-1398) محمد صادق ثابتی', setId: 717 }, ];
        var lastSetData = { set: { id: '650', name: 'فرسنگ هفتم راه ابریشم (ریاضیات جامع تجربی) (ویژۀ 12 بهمن تا 2 اسفند 98) محمد صادق ثابتی', url: { web: 'http://localhost/set/650' } }, files: { pamphlets: [ { name: 'تورق فرسنگ هفتم', file: { pamphlet: [ { link: 'http://localhost/d/eyJpdiI6IkFFQ2M3UzduN2pZQlJRMHh3TkhZSUE9PSIsInZhbHVlIjoidER1UDZWaVppT0o5czkxZXJnbjhUZEk1TjlKaUkrOGh4K0VkSXV6UmpFaGlsZE1zczR2dVdSdjRIR3dEQ1wvMGFIQnFGUitiZU9RTXZlcmFheHJpeHBjNVdIS1ZzZVFmRUhqQUtrSE1lRFR0TEsyNGVydElvUmtQUDVGNENGWlwvdndFUnMySGEzazc5blNYeFd4YnloYWxCeVlxdmZxS2l6TzBNZXhFbzRcL3ZVPSIsIm1hYyI6Ijk5NDQ5ZjJmMWYwZGM1YjlmNWVmNTFmZTI3OGQ2ZWI1OGUzN2MwYjMyZjA3NTJiOGQwMGFlMjVlODFkZGI1N2IifQ==' } ] }, section: { id: '2', name: 'تورق سریع' } }, { name: 'دفترچه تست فرسنگ هفتم (لگاریتم)', file: { pamphlet: [ { link: 'http://localhost/d/eyJpdiI6Imk4aHpweGxGRHNNVnJrUGl4WFBCUkE9PSIsInZhbHVlIjoiSVNzVkRNU3J2NjV6SUx1SjN3VG0zczRteks3cGxDd0dTdnpxTm1WXC9TRmd3Y1M0QnFwZFh5enRlSlBlZGlRQnJMZjRKVVhiYitzTlJjK0UxQnpYclJ5dGZFTUtSc1J3QWF5U3RIQ09GeGZmZ083eWhpaFM1a0RpVHNMVkhzZEt5TmNPSWR4Mm5nK2lxa0FvdFwvQXVWeVFma3p1aUJycTV4aWZKT243bmhSZ1U9IiwibWFjIjoiYmI1NGRlMmZiOTBkY2QyMDlhNjNlOWYzOGE3NDllOTgxNWIxYzliNjg0M2E1ZTIxMDkyMjRlOWQ4MzkxMTFkOSJ9' } ] }, section: { id: '3', name: 'حل تست' } }, ], videos: [ { title: 'راهنمای استفاده از فیلم های فرسنگ هفتم', thumbnail: 'https://cdn.alaatv.com/media/thumbnails/650/650000zero.jpg', url: { web: 'http://localhost/c/19287' }, section: { id: '1', name: 'تابلو راهنما' } }, { title: 'فرسنگ هفتم (قسمت اول)، تورق: لگاریتم (قسمت اول)', thumbnail: 'https://cdn.alaatv.com/media/thumbnails/650/650001zone.jpg', url: { web: 'http://localhost/c/19288' }, section: { id: '2', name: 'تورق سریع' } }, { title: 'فرسنگ هفتم (قسمت دوم)، تورق: لگاریتم (قسمت دوم)', thumbnail: 'https://cdn.alaatv.com/media/thumbnails/650/650002ttwo.jpg', url: { web: 'http://localhost/c/19289' }, section: { id: '2', name: 'تورق سریع' } }, { title: 'فرسنگ هفتم (قسمت سوم)، تورق: کاربرد مشتق (بهینه سازی)', thumbnail: 'https://cdn.alaatv.com/media/thumbnails/650/650003thre.jpg', url: { web: 'http://localhost/c/19306' }, section: { id: '2', name: 'تورق سریع' } }, { title: 'فرسنگ هفتم (قسمت چهارم)، حل تست: لگاریتم (تست های 1 تا 16)', thumbnail: 'https://cdn.alaatv.com/media/thumbnails/650/650004four.jpg', url: { web: 'http://localhost/c/19307' }, section: { id: '3', name: 'حل تست' } }, { title: 'فرسنگ هفتم (قسمت پنجم)، حل تست: لگاریتم (تست های 17 تا 31)', thumbnail: 'https://cdn.alaatv.com/media/thumbnails/650/650005five.jpg', url: { web: 'http://localhost/c/19314' }, section: { id: '3', name: 'حل تست' } }, { title: 'فرسنگ هفتم (قسمت ششم)، حل تست: لگاریتم (تست های 32 تا 46)', thumbnail: 'https://cdn.alaatv.com/media/thumbnails/650/650006zsix.jpg', url: { web: 'http://localhost/c/19315' }, section: { id: '3', name: 'حل تست' } }, { title: 'فرسنگ هفتم (قسمت هفتم)، حل تست: لگاریتم (تست های 47 تا 72)', thumbnail: 'https://cdn.alaatv.com/media/thumbnails/650/650007seve.jpg', url: { web: 'http://localhost/c/19333' }, section: { id: '3', name: 'حل تست' } }, { title: 'فرسنگ هفتم (قسمت هشتم)، حل تست: لگاریتم (تست های 73 تا 90)', thumbnail: 'https://cdn.alaatv.com/media/thumbnails/650/650008eigh.jpg', url: { web: 'http://localhost/c/19334' }, section: { id: '3', name: 'حل تست' } }, ] } };
        var hasUserPurchasedRaheAbrisham = 0; </script>

    <script src="{{ mix('/js/product-show.js') }}"></script>
    <script src="{{ asset('/acm/AlaatvCustomFiles/js/page/product/product-show.js') }}"></script>
@endsection
