<?php
/**
 * Created by PhpStorm.
 * User: mohamamad
 * Date: 11/9/2016
 * Time: 4:41 PM
 */

return [
    // Default Roles
    'ROLE_ADMIN'                                  => 'admin',
    'ROLE_CONSULTANT'                             => 'consultant',
    'ROLE_TECH'                  => 'tech',
    'ROLE_FINANCE_EMPLOYEE'      => 'financeEmployee',
    'EMPLOYEE_ROLE'              => 'employee',
    'ROLE_EMPLOYEE'              => 6,
    'ROLE_TEACHER'               => 'teacher',
    'ROLE_TEACHER_ID'            => 10,
    'BOOK_POST_MAN_ROLE'         => 'bookPostMan',
    'SHARIF_SCHOOL_REGISTER'     => 'sharifSchoolRegister',

    // Permissions :
    'ADMIN_PANEL_ACCESS'         => 'adminPanel',
    'GIVE_SYSTEM_ROLE'           => 'giveSystemRole',
    'USER_ADMIN_PANEL_ACCESS'    => 'userAdminPanel',
    'PRODUCT_ADMIN_PANEL_ACCESS' => 'productAdminPanel',
    'CONTENT_ADMIN_PANEL_ACCESS' => 'contentAdminPanel',
    'SMS_ADMIN_PANEL_ACCESS'     => 'smsAdminPanel',
    'ORDER_ADMIN_PANEL_ACCESS'   => 'orderAdminPanel',
    'SITE_CONFIG_ADMIN_PANEL_ACCESS'              => 'siteConfigAdminPanel',
    'PARTICULAR_ADMIN_PANELS'                     => 'particularAdminPanel',
    'WALLET_ADMIN_PANEL'                          => 'walletAdminPanel',
    'ALAA_FAMILTY'                                => 'alaaFamily',
    'LIST_ASSIGNMENT_ACCESS'                      => 'listAssignment',
    'INSERT_ASSIGNMENT_ACCESS'                    => 'insertAssignment',
    'EDIT_ASSIGNMENT_ACCESS'                      => 'editAssignment',
    'REMOVE_ASSIGNMENT_ACCESS'                    => 'removeAssignment',
    'SHOW_ASSIGNMENT_ACCESS'                      => 'showAssignment',
    'LIST_CONSULTATION_ACCESS'                    => 'listConsultation',
    'INSERT_CONSULTATION_ACCESS'                  => 'insertConsultation',
    'EDIT_CONSULTATION_ACCESS'                    => 'editConsultation',
    'REMOVE_CONSULTATION_ACCESS'                  => 'removeConsultation',
    'SHOW_CONSULTATION_ACCESS'                    => 'showConsultation',
    'LIST_USER_ACCESS'                            => 'listUser',
    'INSERT_USER_ACCESS'                          => 'insertUser',
    'EDIT_USER_ACCESS'                            => 'editUser',
    'REMOVE_USER_ACCESS'                          => 'removeUser',
    'SHOW_USER_ACCESS'                            => 'showUser',
    'SEND_SMS_TO_USER_ACCESS'                     => 'sendSMSUser',
    'INSERT_USER_BON_ACCESS'                      => 'insertUserBon',
    'LIST_USER_BON_ACCESS'                        => 'listUserBon',
    'REMOVE_USER_BON_ACCESS'                      => 'removeUserBon',
    'DOWNLOAD_ASSIGNMENT_ACCESS'                  => 'downloadAssignment',
    'DOWNLOAD_PRODUCT_FILE'                       => 'downloadProductFile',
    'LIST_PRODUCT_ACCESS'                         => 'listProduct',
    'INSERT_PRODUCT_ACCESS'                       => 'insertProduct',
    'EDIT_PRODUCT_ACCESS'                         => 'editProduct',
    'REMOVE_PRODUCT_ACCESS'                       => 'removeProduct',
    'COPY_PRODUCT_ACCESS'                         => 'copyProduct',
    'SHOW_PRODUCT_ACCESS'                         => 'showProduct',
    'LIST_ORDER_ACCESS'                           => 'listOrder',
    'INSERT_ORDER_ACCESS'                         => 'insertOrder',
    'EDIT_ORDER_ACCESS'                           => 'editOrder',
    'REMOVE_ORDER_ACCESS'                         => 'removeOrder',
    'SHOW_ORDER_ACCESS'                           => 'showOrder',
    'SHOW_OPENBYADMIN_ORDER'                      => 'showOpenByAdminOrders',
    'LIST_PERMISSION_ACCESS'                      => 'listPermission',
    'INSERT_PERMISSION_ACCESS'                    => 'insertPermission',
    'EDIT_PERMISSION_ACCESS'                      => 'editPermission',
    'REMOVE_PERMISSION_ACCESS'                    => 'removePermission',
    'SHOW_PERMISSION_ACCESS'                      => 'showPermission',
    'INSET_USER_ROLE'                             => 'insertUserRole',
    'SHOW_USER_ROLE'                              => 'showUserRole',
    'LIST_COUPON_ACCESS'                          => 'listCoupon',
    'INSERT_COUPON_ACCESS'                        => 'insertCoupon',
    'EDIT_COUPON_ACCESS'                          => 'editCoupon',
    'REMOVE_COUPON_ACCESS'                        => 'removeCoupon',
    'SHOW_COUPON_ACCESS'                          => 'showCoupon',
    'LIST_QUESTION_ACCESS'                        => 'listStudentQuestion',
    'CONSULTANT_PANEL_ACCESS'                     => 'consultantPanel',
    'SHOW_QUESTION_ACCESS'                        => 'showStudentQuestion',
    'LIST_ATTRIBUTE_ACCESS'                       => 'listAttribute',
    'INSERT_ATTRIBUTE_ACCESS'                     => 'insertAttribute',
    'EDIT_ATTRIBUTE_ACCESS'                       => 'editAttribute',
    'REMOVE_ATTRIBUTE_ACCESS'                     => 'removeAttribute',
    'SHOW_ATTRIBUTE_ACCESS'                       => 'showAttribute',
    'LIST_ATTRIBUTESET_ACCESS'                    => 'listAttributeset',
    'INSERT_ATTRIBUTESET_ACCESS'                  => 'insertAttributeset',
    'EDIT_ATTRIBUTESET_ACCESS'                    => 'editAttributeset',
    'REMOVE_ATTRIBUTESET_ACCESS'                  => 'removeAttributeset',
    'SHOW_ATTRIBUTESET_ACCESS'                    => 'showAttributeset',
    'LIST_ATTRIBUTEVALUE_ACCESS'                  => 'listAttributevalue',
    'INSERT_ATTRIBUTEVALUE_ACCESS'                => 'insertAttributevalue',
    'EDIT_ATTRIBUTEVALUE_ACCESS'                  => 'editAttributevalue',
    'REMOVE_ATTRIBUTEVALUE_ACCESS'                => 'removeAttributevalue',
    'SHOW_ATTRIBUTEVALUE_ACCESS'                  => 'showAttributevalue',
    'LIST_ATTRIBUTEGROUP_ACCESS'                  => 'listAttributegroup',
    'INSERT_ATTRIBUTEGROUP_ACCESS'                => 'insertAttributegroup',
    'EDIT_ATTRIBUTEGROUP_ACCESS'                  => 'editAttributegroup',
    'REMOVE_ATTRIBUTEGROUP_ACCESS'                => 'removeAttributegroup',
    'SHOW_ATTRIBUTEGROUP_ACCESS'                  => 'showAttributegroup',
    'LIST_TRANSACTION_ACCESS'                     => 'listTransaction',
    'SHOW_TRANSACTION_TOTAL_COST_ACCESS'          => 'showTransactionTotalCost',
    'SHOW_TRANSACTION_TOTAL_FILTERED_COST_ACCESS' => 'showTransactionTotalFilteredCost',
    'EDIT_TRANSACTION_ACCESS'                     => 'editTransaction',
    'INSERT_TRANSACTION_ACCESS'                   => 'insertTransaction',
    'SHOW_TRANSACTION_ACCESS'                     => 'showTransaction',
    'REMOVE_TRANSACTION_ACCESS'                   => 'removeTransaction',
    'EDIT_TRANSACTION_ORDERID_ACCESS'             => 'editTransactionOrderID',
    'LIST_MBTIANSWER_ACCESS'                      => 'listMBTIAnswer',
    'LIST_CONTACT_ACCESS'                         => 'listContact',
    'INSERT_CONTACT_ACCESS'                       => 'insertContact',
    'EDIT_CONTACT_ACCESS'                         => 'editContact',
    'REMOVE_CONTACT_ACCESS'                       => 'removeContact',
    'SHOW_USER_EMAIL'                             => 'showUserEmail',
    'SHOW_USER_MOBILE'                            => 'showUserMobile',
    'SHOW_ARTICLE_ACCESS'                         => 'showArticle',
    'LIST_ARTICLE_ACCESS'                         => 'listArticle',
    'INSERT_ARTICLE_ACCESS'                       => 'insertArticle',
    'EDIT_ARTICLE_ACCESS'                         => 'editArticle',
    'REMOVE_ARTICLE_ACCESS'                       => 'removeArticle',
    'SHOW_ARTICLECATEGORY_ACCESS'                 => 'showArticlecategory',
    'LIST_ARTICLECATEGORY_ACCESS'                 => 'listArticlecategory',
    'INSERT_ARTICLECATEGORY_ACCESS'               => 'insertArticlecategory',
    'EDIT_ARTICLECATEGORY_ACCESS'                 => 'editArticlecategory',
    'REMOVE_ARTICLECATEGORY_ACCESS'               => 'removeArticlecategory',
    'LIST_SLIDESHOW_ACCESS'                       => 'listSlideShow',
    'INSERT_SLIDESHOW_ACCESS'                     => 'insertSlideShow',
    'EDIT_SLIDESHOW_ACCESS'                       => 'editSlideShow',
    'REMOVE_SLIDESHOW_ACCESS'                     => 'removeSlideShow',
    'SHOW_SLIDESHOW_ACCESS'                       => 'showSlideShow',
    'LIST_CONFIGURE_PRODUCT_ACCESS'               => 'listConfigureProduct',
    'INSERT_CONFIGURE_PRODUCT_ACCESS'             => 'insertConfigureProduct',
    'EDIT_CONFIGURE_PRODUCT_ACCESS'               => 'editConfigureProduct',
    'REMOVE_CONFIGURE_PRODUCT_ACCESS'             => 'removeConfigureProduct',
    'SHOW_CONFIGURE_PRODUCT_ACCESS'               => 'showConfigureProduct',
    'LIST_PRODUCT_FILE_ACCESS'                    => 'listProductFile',
    'LIST_PRODUCT_SAMPLE_PHOTO_ACCESS'            => 'listProductSamplePhoto',
    'INSERT_PRODUCT_SAMPLE_PHOTO_ACCESS'          => 'insertProductSamplePhoto',
    'EDIT_PRODUCT_SAMPLE_PHOTO_ACCESS'            => 'editProductSamplePhoto',
    'REMOVE_PRODUCT_SAMPLE_PHOTO_ACCESS'          => 'removeProductSamplePhoto',
    'INSERT_PRODUCT_FILE_ACCESS'                  => 'insertProductFile',
    'EDIT_PRODUCT_FILE_ACCESS'                    => 'editProductFile',
    'REMOVE_PRODUCT_FILE_ACCESS'                  => 'removeProductFile',
    'SHOW_PRODUCT_FILE_ACCESS'                    => 'showProductFile',
    'LIST_SITE_CONFIG_ACCESS'                     => 'listSiteSetting',
    'INSERT_SITE_CONFIG_ACCESS'                   => 'insertSiteSetting',
    'EDIT_SITE_CONFIG_ACCESS'                     => 'editSiteSetting',
    'REMOVE_SITE_CONFIG_ACCESS'                   => 'removeSiteSetting',
    'SHOW_SITE_CONFIG_ACCESS'                     => 'showSiteSetting',
    'LIST_EVENTRESULT_ACCESS'                     => 'listEventResult',
    'INSET_EVENTRESULT_ACCESS'                    => 'insertEventResult',
    'LIST_SHARIF_REGISTER_ACCESS'                 => 'listSharifRegister',
    'LIST_BELONGING_ACCESS'                       => 'listBelonging',
    'INSERT_BELONGING_ACCESS'                     => 'insertBelonging',
    'REMOVE_BELONGING_ACCESS'                     => 'removeBelonging',
    'LIST_EDUCATIONAL_CONTENT_ACCESS'             => 'listEducationalContent',
    'INSERT_EDUCATIONAL_CONTENT_ACCESS'           => 'insertEducationalContent',
    'EDIT_EDUCATIONAL_CONTENT'                    => 'editEducationalContent',
    'REMOVE_EDUCATIONAL_CONTENT_ACCESS'           => 'removeEducationalContent',
    'SHOW_EDUCATIONAL_CONTENT_ACCESS'             => 'showEducationalContent',
    'REDIRECT_EDUCATIONAL_CONTENT_ACCESS'         => 'redirectEducationalContent',
    'REMOVE_EDUCATIONAL_CONTENT_FILE_ACCESS'      => 'removeEducationalContentFile',
    'REPORT_ADMIN_PANEL_ACCESS'                   => 'reportAdminPanelAccess',
    'INSERT_EMPLOPYEE_WORK_SHEET'                 => 'insertEmployeeWorkSheet',
    'LIST_EMPLOPYEE_WORK_SHEET'                   => 'listEmployeeWorkSheet',
    'EDIT_EMPLOPYEE_WORK_SHEET'                   => 'editEmployeeWorkSheet',
    'REMOVE_EMPLOPYEE_WORK_SHEET'                 => 'removeEmployeeWorkSheet',
    'ORDER_ANY_THING'                             => 'orderAnyThing',
    'GET_BOOK_SELL_REPORT'                        => 'getBookSellReport',
    'SEE_PAID_COST'                               => 'seePaidCost',
    'INSERT_MAJOR'                                => 'insertMajor',
    'GET_USER_REPORT'                             => 'getUserReport',
    'TELEMARKETING_PANEL_ACCESS'                  => 'telemarketingPanel',
    'LIST_ORDERPRODUCT_ACCESS'                    => 'listOrderproduct',
    'INSERT_ORDERPRODUCT_ACCESS'                  => 'insertOrderproduct',
    'REMOVE_ORDERPRODUCT_ACCESS'                  => 'removeOrderproduct',
    'UPDATE_ORDERPRODUCT_ACCESS'                  => 'updateOrderproduct',
    'SHOW_ORDERPRODUCT_ACCESS'                    => 'showOrderproduct',
    'RESTORE_ORDERPRODUCT_ACCESS'                 => 'restoreOrderproduct',
    'CHECKOUT_ORDERPRODUCT_ACCESS'                => 'checkoutOrderproduct',
    'SHOW_USER_TOTAL_BON_NUMBER'                  => 'showUserTotalBonNumber',
    'INSERT_ACTIVE_CONTENT'                       => 'insertActiveContent',
    'CHANGE_TO_PAID_CONTENT'                      => 'changeToPaidContent',
    'SHOW_CONTENT_SET_ACCESS'                     => 'showContentset',
    'LIST_CONTENT_SET_ACCESS'                     => 'listContentset',
    'INSERT_CONTENT_SET_ACCESS'                   => 'insertContentset',
    'EDIT_CONTENT_SET_ACCESS'                     => 'editContentset',
    'REMOVE_CONTENT_SET_ACCESS'                   => 'removeContentset',
    'SHOW_SALES_REPORT'          => 'showSalesReport',
    'LIST_BLOCK_ACCESS'          => 'listBlock',
    'INSERT_BLOCK_ACCESS'        => 'insertBlock',
    'EDIT_BLOCK_ACCESS'          => 'editBlock',
    'REMOVE_BLOCK_ACCESS'        => 'removeBlock',
    'LIVE_STOP_ACCESS'           => 'stopLive',
    'LIVE_PLAY_ACCESS'           => 'playLive',
    'GIVE_WALLET_CREDIT'         => 'giveWalletCredit',
    'SEE_ORDER_FILTERS'          => 'seeOrderFilters',
    'SEE_ORDER_IDENTITY_FILTERS' => 'seeOrderIdentityFilters',

    //Technician
    'SET_TECH_CODE'              => 'insertTechCode',
    'UPDATE_TECH_CODE'           => 'updateTechCode',

    //bons
    'BON1'                       => 'alaa',
    'BON2'                       => 'alaaPoint',

    //fileSystem disks
    'DISK1'                      => 'profileImage',
    'DISK2'                      => 'assignmentQuestionFile',
    'DISK3'                      => 'assignmentSolutionFile',
    'DISK4'                      => 'productImage',
    'DISK5'                      => 'productCatalog_PDF',
    'DISK6'                      => 'consultingAudioQuestions',
    'DISK7'                      => 'consultationThumbnail',
    'DISK8'                                       => 'articleImage',
    'DISK9'                                       => 'homeSlideShowPic',
    'DISK10'                                      => 'orderFile',
    'DISK11'                                      => 'general',
    'DISK12'                                      => 'belongingIDCard',
    'DISK13'                                      => 'productFile',
    'DISK14'                                      => 'eventReport',
    'DISK15'                                      => 'articleSlideShowPic',
    'DISK16'                                      => 'digitalSignatureCertificates',
    'DISK17'                                      => 'digitalSignatures',
    'DISK18'                                      => 'exam',
    'DISK18_CLOUD'                                => 'examSftp',
    'DISK19'                                      => 'pamphlet',
    'DISK19_CLOUD'               => 'pamphletSftp',
    'DISK20'                     => 'book',
    'DISK20_CLOUD'               => 'bookSftp',
    'DISK21'                     => 'productImageSFTP',
    'DISK22'                     => 'homeSlideShowPicSFTP',
    'DISK23'                     => 'setImageSFTP',
    'DISK24'                     => 'profileImageSFTP',
    'DISK25'                     => 'contentThumbnailSFTP',

    'DISK_FREE_CONTENT'              => 'alaaCdnSFTP',
    'DISK_PRODUCT_CONTENT'           => 'productFileSFTP',

    //Profile default image
    'PROFILE_DEFAULT_IMAGE'          => 'default_avatar.png',
    'CONSULTATION_DEFAULT_IMAGE'     => 'default_consultant_thumbnail.jpg',
    'ARTICLE_DEFAULT_IMAGE'          => 'default_article_image.png',

    //Mobile verification code wait expiration (in minutes)
    'MOBILE_VERIFICATION_TIME_LIMIT' => '30',
    'MOBILE_VERIFICATION_WAIT_TIME'  => '4',
    //waiting time between sending two mobile verification code sms
    'GENERATE_PASSWORD_WAIT_TIME'    => '14',
    //waiting time between sending two password sms

    //Number of mbti questions (it is temporary)
    'MBTI_NUMBER_OF_QUESTIONS'       => '80',

    //loading gif
    'FILTER_LOADING_GIF'             => '/acm/extra/loading-cogs.gif',
    'ADMIN_LOADING_BAR_GIF'          => '/acm/extra/filter-loading-bar.gif',

    //sms payment
    'COST_PER_SMS_1'                 => 100,
    'COST_PER_SMS_2'                 => 110,
    'COST_PER_SMS_3'                 => 130,

    'SMS_PROVIDER_NUMBER' => [
        'phone' => [
            98100020400      => 98100020400,
            985000125475     => 985000125475,
            9810000066009232 => 9810000066009232,
            98500010409232   => 98500010409232,
            981000958        => 981000958,
            985000189        => 985000189,
            985000958        => 985000958,
            //            '98sim'          => '98sim',
        ],
        'cost'  => [
            98100020400      => 100,
            985000125475     => 85,
            9810000066009232 => 100,
            98500010409232   => 85,
            981000958        => 100,
            985000189        => 85,
            985000958        => 85,
            //            '98sim'          => ,
        ],
    ],
    'google'              => [
        'analytics' => env('GOOGLE_ANALYTICS', 'UA-43695756-1'),
    ],


    'UI_META_TITLE_LIMIT'       => 70,
    'UI_META_KEYWORD_LIMIT'     => 155,
    'UI_META_DESCRIPTION_LIMIT' => 155,
    'META_TITLE_LIMIT'          => 129,
    'META_KEYWORDS_LIMIT'       => 286,
    'META_DESCRIPTION_LIMIT'    => 286,

    'WORKDAY_ID_USUAL'                                    => 1,
    'WORKDAY_ID_EXTRA'                                    => 2,
    'HAMAYESH_PRODUCT'                                    => [
        119,
        123,
        127,
        131,
        135,
        139,
        143,
        147,
        151,
        155,
        159,
        163,
    ],
    'HAMAYESH_CHILDREN'                                   => [
        124,
        125,
        120,
        121,
        164,
        165,
        160,
        161,
        156,
        157,
        152,
        153,
        148,
        149,
        144,
        145,
        140,
        141,
        136,
        137,
        132,
        133,
        128,
        129,
    ],
    'ORDOO_GHEIRE_HOZOORI_NOROOZ_97_PRODUCT'              => [
        196,
        200,
        201,
        203,
        204,
        205,
        206,
    ],
    'ORDOO_GHEIRE_HOZOORI_NOROOZ_97_PRODUCT_ROOT'         => 196,
    'ORDOO_GHEIRE_HOZOORI_NOROOZ_97_PRODUCT_ALLTOGHETHER' => 206,
    'ORDOO_GHEIRE_HOZOORI_NOROOZ_97_PRODUCT_DEFAULT'      => 204,
    'ORDOO_GHEIRE_HOZOORI_NOROOZ_97_PRODUCT_NOT_DEFAULT'  => [
        200,
        201,
        203,
        205,
    ],
    'ORDOO_HOZOORI_NOROOZ_97_PRODUCT'                     => [
        184,
        185,
        186,
    ],
    'EDUCATIONAL_CONTENT_EXCLUDED_PRODUCTS'               => [
        110,
        112,
    ],
    'PRODUCT_SEARCH_EXCLUDED_PRODUCTS'                    => [
        119,
        123,
        127,
        131,
        135,
        139,
        143,
        147,
        151,
        155,
        159,
        163,
    ],

    'ASIATECH_FREE_ADSL'                 => 224,
    'LOTTERY_NAME'                       => '10tir',
    'HAMAYESH_LOTTERY_EXCHANGE_AMOUNT'   => 30000,

    //Cache
    'CACHE_600'                          => env('CACHE_600', 0),
    'CACHE_300'                          => env('CACHE_300', 0),
    'CACHE_60'                           => env('CACHE_60', 0),
    'CACHE_10'                           => env('CACHE_10', 0),
    'CACHE_5'                            => env('CACHE_5', 0),
    'CACHE_3'                            => env('CACHE_3', 0),
    'CACHE_1'                            => env('CACHE_1', 0),
    'CACHE_0'                            => env('CACHE_0', 0),

    //
    'TAG_API_URL'                        => env('TAG_API_URL', null),
    'SERVER'                             => env('SERVER'),
    'CDN_SERVER_NAME'                    => env('CDN_SERVER_NAME', null),
    'PAID_SERVER_NAME'                   => env('PAID_SERVER_NAME', null),
    'DOWNLOAD_SERVER_ROOT'               => env('DOWNLOAD_SERVER_ROOT', null),
    'DOWNLOAD_SERVER_PROTOCOL'           => env('DOWNLOAD_SERVER_PROTOCOL', null),
    'DOWNLOAD_SERVER_MEDIA_PARTIAL_PATH' => env('DOWNLOAD_SERVER_MEDIA_PARTIAL_PATH', null),

    //OrderStatus
    'ORDER_STATUS_OPEN'                  => 1,
    'ORDER_STATUS_CLOSED'                => 2,
    'ORDER_STATUS_CANCELED'              => 3,
    'ORDER_STATUS_OPEN_BY_ADMIN'         => 4,
    'ORDER_STATUS_POSTED'                => 5,
    'ORDER_STATUS_REFUNDED'              => 6,
    'ORDER_STATUS_READY_TO_POST'         => 7,
    'ORDER_STATUS_OPEN_DONATE'           => 8,
    'ORDER_STATUS_PENDING'               => 9,

    'OPEN_ORDER_STATUSES'                    => [1, 4, 8],

    //TRANSACTION STATUSES CONSTANTS
    'TRANSACTION_STATUS_TRANSFERRED_TO_PAY'  => 1,
    'TRANSACTION_STATUS_UNSUCCESSFUL'        => 2,
    'TRANSACTION_STATUS_SUCCESSFUL'          => 3,
    'TRANSACTION_STATUS_PENDING'             => 4,
    'TRANSACTION_STATUS_ARCHIVED_SUCCESSFUL' => 5,
    'TRANSACTION_STATUS_UNPAID'              => 6,
    'TRANSACTION_STATUS_SUSPENDED'           => 7,

    //PAYMENT METHODS CONSTANTS
    'PAYMENT_METHOD_ONLINE'                  => 1,
    'PAYMENT_METHOD_ATM'                     => 2,
    'PAYMENT_METHOD_POS'                     => 3,
    'PAYMENT_METHOD_PAYCHECK'                => 4,
    'PAYMENT_METHOD_WALLET'                  => 5,

    //PAYMENT STATUSES CONSTANTS
    'PAYMENT_STATUS_UNPAID'                  => 1,
    'PAYMENT_STATUS_INDEBTED'                => 2,
    'PAYMENT_STATUS_PAID'                    => 3,
    'PAYMENT_STATUS_VERIFIED_INDEBTED'       => 4,

    'ORDERPRODUCT_CHECKOUT_STATUS_UNPAID'      => 1,
    'ORDERPRODUCT_CHECKOUT_STATUS_PAID'        => 2,

    //USER BON STATUSES CONSTANTS
    'USERBON_STATUS_ACTIVE'                    => 1,
    'USERBON_STATUS_EXPIRED'                   => 2,
    'USERBON_STATUS_USED'                      => 3,

    //PRODUCT TYPES CONSTANTS
    'PRODUCT_TYPE_SIMPLE'                      => 1,
    'PRODUCT_TYPE_CONFIGURABLE'                => 2,
    'PRODUCT_TYPE_SELECTABLE'                  => 3,

    //CONTROLS CONSTANTS
    'CONTROL_SELECT'                           => 1,
    'CONTROL_GROUPED_CHECKBOX'                 => 2,
    'CONTROL_SWITCH'                           => 3,

    //ORDERPRODUCT TYPES CONSTANTS
    'ORDER_PRODUCT_TYPE_DEFAULT'               => 1,
    'ORDER_PRODUCT_GIFT'                       => 2,

    //ORDERPRODUCT INTERRELATIONS
    'ORDER_PRODUCT_INTERRELATION_PARENT_CHILD' => 1,

    //TRANSACTION INTERRELATIONS
    'TRANSACTION_INTERRELATION_PARENT_CHILD'   => 1,

    //PRODUCT INTERRELATIONS
    'PRODUCT_INTERRELATION_GIFT'               => 1,

    //DISCOUNT TYPES
    'DISCOUNT_TYPE_PERCENTAGE'                 => 1,
    'DISCOUNT_TYPE_COST'                       => 2,

    //PRODUCT FILE TYPES
    'PRODUCT_FILE_TYPE_PAMPHLET'               => 1,
    'PRODUCT_FILE_TYPE_VIDEO'                  => 2,

    //CONTENT TYPES
    'CONTENT_TYPE_PAMPHLET'                    => 1,
    'CONTENT_TYPE_VIDEO'                       => 8,
    'CONTENT_TYPE_ARTICLE'                     => 9,

    //WALLET TYPES
    'WALLET_TYPE_MAIN'                         => 1,
    'WALLET_TYPE_GIFT'                         => 2,

    //USER STATUSES
    'USER_STATUS_ACTIVE'                       => 1,
    'USER_STATUS_INACTIVE'                     => 2,

    //COUPON TYPES
    'COUPON_TYPE_OVERALL'                      => 1,
    'COUPON_TYPE_PARTIAL'                      => 2,

    'ATTRIBUTE_TYPE_MAIN'        => 1,
    'ATTRIBUTE_TYPE_EXTRA'       => 2,
    'ATTRIBUTE_TYPE_INFORMATION' => 3,

    'EMPLOYEE_OVERTIME_STATUS_UNCONFIRMED' => 1,
    'EMPLOYEE_OVERTIME_STATUS_CONFIRMED'   => 2,
    'EMPLOYEE_OVERTIME_STATUS_REJECTED'    => 3,

    'JALALI_CALENDER'   => [
        [
            'month'       => 'مهر',
            'periodBegin' => '2019-09-23',
            'periodEnd'   => '2019-10-23',
        ],
        [
            'month'       => 'آبان',
            'periodBegin' => '2019-10-23',
            'periodEnd'   => '2019-11-22',
        ],
        [
            'month'       => 'آذر',
            'periodBegin' => '2019-11-22',
            'periodEnd'   => '2019-12-22',
        ],
        [
            'month'       => 'دی',
            'periodBegin' => '2019-12-22',
            'periodEnd'   => '2020-01-21',
        ],
        [
            'month'       => 'بهمن',
            'periodBegin' => '2020-01-21',
            'periodEnd'   => '2020-02-20',
        ],
        [
            'month'       => 'اسفند',
            'periodBegin' => '2020-02-20',
            'periodEnd'   => '2020-03-20',
        ],
        [
            'month'       => 'فروردین',
            'periodBegin' => '2020-03-20',
            'periodEnd'   => '2020-04-20',
        ],
        [
            'month'       => 'اردیبهشت',
            'periodBegin' => '2020-04-20',
            'periodEnd'   => '2020-05-21',
        ],
        [
            'month'       => 'خرداد',
            'periodBegin' => '2020-05-21',
            'periodEnd'   => '2020-06-21',
        ],
        [
            'month'       => 'تیر',
            'periodBegin' => '2020-06-21',
            'periodEnd'   => '2020-07-22',
        ],
        [
            'month'       => 'مرداد',
            'periodBegin' => '2020-07-22',
            'periodEnd'   => '2020-08-22',
        ],
        [
            'month'       => 'شهریور',
            'periodBegin' => '2020-08-22',
            'periodEnd'   => '2020-09-22',
        ],
    ],
    'JALALI_ALL_MONTHS' => [
        'مهر',
        'آبان',
        'آذر',
        'دی',
        'بهمن',
        'اسفند',
        'فروردین',
        'اردیبهشت',
        'خرداد',
        'تیر',
        'مرداد',
        'شهریور',
    ],
    'ALL_DAYS_OF_MONTH' => [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
    ],
];
